language: python
jobs:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
install:
  - sudo rm -f /etc/boto.cfg
  - pip install -r requirements.txt
script:
  - python3 text_classifier.py
