language: python
jobs:
  include:
#     - name: "Python 3.7 on Xenial Linux"
#       python: 3.7           # this works for Linux but is ignored on macOS or Windows
#     - name: "Python 3.7 on macOS"
#       os: osx
#       osx_image: xcode11.5  # Python 3.7 running on macOS 10.14.4
#       language: shell       # 'language: python' is an error on Travis CI macOS
#     - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - if os != windows; then
      sudo rm -f /etc/boto.cfg
    fi
  - pip install -r requirements.txt
script:
  - python3 text_classifier.py || python text_classifier.py
